swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Expenses tracker API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /expense:
    get:
      operationId: "expense.read"
      tags:
        - "Expense"
      summary: "The expense data structure supported by the server application"
      description: "Read the list of expense"
      responses:
        200:
          description: "Successful read expense list"
          schema:
            type: "array"
            items:
              properties:
                amount:
                  type: "integer"
                desc:
                  type: "string"
                pay_method:
                  type: "string"
                timestamp:
                  type: "string"
                  format: "date"
