language: python
python: ['3.7']
script:
- coverage run -m pytest --disable-pytest-warnings
install:
- pip install -r development.txt
after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
