language: python
python:
- 3.7.4
script:
- travis_wait 40 coverage run -m pytest --disable-pytest-warnings
install:
- pip install -r development.txt
- pip install --upgrade attrs
after_success:
- codecov
- bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
branches:
  only:
  - master
