language: python
python:
- 3.6.7
script:
- travis_wait 40 coverage run -m pytest --disable-pytest-warnings
install:
- pip install -r development.txt
after_success:
- codecov
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: shlomiLan#
  password:
    secure: nS1fKRrjnLtRzuK0ZvDpzgVIosVsrujafiooImG1q/RrcVYuNE9Ps6ioPoosb2SCZAOoaitptNEshKIAPwhFYAZ2ChzEpRov4LXL1fhOtQq7lNkJZxykh8jOJ1jNrQGk/+LtV1jOgyNpPsJ5MYQVzAx/Y5lAVZ3pkNQZO3MtaTha2O4fZcJ+jxegrSl1U1HTlkZ81JdXZNJMVmDa0LyCQCseDYrNL0i1w+d5jqhfnW8soRQuHLBp1UoVFF3MNG7uQa2TQ9XvzHhGNLsgo/fvuB3vXFJe7j/Ppxfo8vKwhYe8lw0ZcWktYnwDIq+0h9UHrGw8NI3ceqfsbT6YHrs+J53DVtXYPlLlyFnQuxbGSbZ6iXRIOBfS4jacJfejG/YEIEySSIqk/yGfNj8BuEEU8KSJoeFlC2SkwtL190ij0jSRTBc+wehQy4A0faH9ioeT2ugf2IZuv50BvrhW2CJuH6D8lME/nLnXzv9Odu2ZWicjo0SSHtFoJ6HZDm6IkoTJwIKhE8onhlrC4vl2tOS7usHVCBfX9w58FMzuvenEe0TX9rMJWl12KNRgZ+GIKB0acp2bIC2bhju1lQtbkMddT/aAZErn4CJOIiuGnLW5Njcd9n5qNVbp9v0roQDpp5aLlIlTS3RHEvnclRkDy8zhNdqwBc0VgtDv02MBCfjNslA=
branches:
  only:
  - master