dist: xenial
language: python
python:
  - 3.6.7
script:
#  - travis_wait 40 coverage run -m pytest --disable-pytest-warnings
  - inv test.test --file slots_tracker_server/tests/test_client.py
before_install:
  #  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - google-chrome --version
  - google-chrome-stable --version
install:
  - pip install -r development.txt
  - pip install --upgrade attrs
after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
branches:
  only:
    - master
addons:
  chrome: stable
