before_install: [openssl aes-256-cbc -K $encrypted_33d6361e9e6d_key -iv $encrypted_33d6361e9e6d_iv
    -in /Users/shlomilanton/workscpace/slots_tracker_server/resources/credentials.json.enc
    -out ~\/workscpace/slots_tracker_server/resources/credentials.json -d]
env:
  global: {APP_SETTINGS: config.DevelopmentConfig, FLASK_APP: slots_tracker_server,
    FLASK_ENV: development}
language: python
python: ['3.6']
script: pytest
