dist: trusty
language: python
python:
- 3.6.7
script:
- travis_wait 40 coverage run -m pytest --disable-pytest-warnings
install:
- pip install -r development.txt
- pip install --upgrade attrs
after_success:
- codecov
- python-codacy-coverage -r coverage.xml
branches:
  only:
  - master
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
